CREATE TABLE FIRMA
(
	ID INTEGER PRIMARY KEY, 
	PIB VARCHAR2(30) UNIQUE NOT NULL,
	IME_FIRME VARCHAR2(30) NOT NULL
);

CREATE TABLE ZATVORSKA_JEDINICA
(
	ID INTEGER PRIMARY KEY,
	SIFRA VARCHAR2(30) UNIQUE NOT NULL,
	NAZIV VARCHAR2(30) NOT NULL,
	ADRESA VARCHAR2(30) NOT NULL,
	KAPACITET INTEGER NOT NULL,
	OTVORENI_F CHAR(1) CHECK (OTVORENI_F IN ('Y', 'N')),
	POLUOTVORENI_F CHAR(1) CHECK (POLUOTVORENI_F IN ('Y', 'N')),
	PERIOD_ZAKLJUCAVANJA VARCHAR2(30),
	STROGI_F CHAR(1) CHECK (STROGI_F IN 'Y', 'N')),	
	SETNJA VARCHAR2(30),
	ID_UPRAVNIKA INTEGER NOT NULL,
	--CONSTRAINT ZATVOR_ZAPOSLENI_FK FOREIGN KEY (ID_UPRAVNIKA) REFERENCES ZAPOSLENI(ID) ON DELETE CASCADE
);

CREATE TABLE ZATVORENIK
(
	ID INTEGER PRIMARY KEY,
	JMBG VARCHAR2(13) UNIQUE NOT NULL,
	IME VARCHAR2(15) NOT NULL,
	PREZIME VARCHAR2(30) NOT NULL,
	POL CHAR(1) CHECK (POL IN ('M', 'Z')),
	BROJ VARCHAR2(5) UNIQUE NOT NULL,
	ADRESA VARCHAR2(40),
	DATUM_SASLUSANJA DATE,
	STATUS_USLOVNOG_OTPUSTA CHAR(1) CHECK (STATUS_USLOVNOG_OTPUSTA IN ('Y', 'N')),
	ID_ZATVORSKE_JEDINICE INTEGER NOT NULL,
	CONSTRAINT ZATVORENIK_ZATVOR_FK FOREIGN KEY (ID_ZATVORSKE_JEDINICE) REFERENCES ZATVORSKA_JEDINICA(ID) ON DELETE CASCADE
);

CREATE TABLE ADVOKAT
(
	ID INTEGER PRIMARY KEY,
	JMBG VARCHAR2(13) UNIQUE NOT NULL,
	IME VARCHAR2(15) NOT NULL,
	PREZIME VARCHAR2(30) NOT NULL,
	POL CHAR (1) CHECK (POL IN ('M', 'Z'))
);

CREATE TABLE ZAPOSLENI
(
	ID INTEGER PRIMARY KEY,
	JMBG VARCHAR2(13) UNIQUE NOT NULL,
	IME VARCHAR2(15) NOT NULL,
	PREZIME VARCHAR2(30) NOT NULL,
	POL CHAR(1) CHECK (POL IN ('M', 'Z')),
	DATUM_PPZ DATE,
	NAZIV_RADNOG_MESTA VARCHAR2(30) NOT NULL,
	A_STRUCNA_SPREMA VARCHAR2(30),
	A_ZANIMANJE VARCHAR2(30),
	A_POZICIJA VARCHAR(30),
	ID_ZATVORSKE_JEDINICE INTEGER NOT NULL,
	DATUM_POCETKA_RADA DATE NOT NULL,
	CONSTRAINT ZAPOSLENI_ZATVOR_FK FOREIGN KEY (ID_ZATVORSKE_JEDINICE) REFERENCES ZATVORSKA_JEDINICA(ID) ON DELETE CASCADE
);

CREATE TABLE LEKARSKI_PREGLED
(
	ID INTEGER PRIMARY KEY,
	ID_ZAPOSLENOG INTEGER,
	NAZIV_USTANOVE VARCHAR2(30) NOT NULL,
	DATUM DATE NOT NULL,
	ADRESA_USTANOVE VARCHAR2(30) NOT NULL,
	LEKAR VARCHAR(30) NOT NULL,
	CONSTRAINT LEKARSKI_PREGLED_ZAPOSLENI_FK FOREIGN KEY (ID_ZAPOSLENOG) REFERENCES ZAPOSLENI(ID) ON DELETE CASCADE
);

CREATE TABLE DOZVOLA_ZA_ORUZJE
(
	ID INTEGER PRIMARY KEY,
	ID_ZAPOSLENOG INTEGER NOT NULL,
	DATUM DATE NOT NULL,
	SIFRA_DOZVOLE VARCHAR2(30) UNIQUE NOT NULL,
	POLICIJSKA_UPRAVA VARCHAR2(30) NOT NULL,
	CONSTRAINT DOZVOLA_ZA_ORUZJE_ZAPOSLENI_FK FOREIGN KEY (ID_ZAPOSLENOG) REFERENCES ZAPOSLENI(ID) ON DELETE CASCADE
);

CREATE TABLE PRESTUP
(
	ID INTEGER PRIMARY KEY,
	NAZIV VARCHAR2(30) UNIQUE NOT NULL,
	OPIS VARCHAR2(255),
	MINIMALNA_KAZNA  VARCHAR2(30) NOT NULL,
	MAXIMALNA_KAZNA VARCHAR2(30) NOT NULL,
	KATEGORIJA VARCHAR2(60) NOT NULL
);

CREATE TABLE ZASTUPA
(
	ID INTEGER PRIMARY KEY,
	ID_ZATVORENIKA INTEGER NOT NULL,
	ID_ADVOKATA INTEGER NOT NULL,
	ZASTUPA_OD DATE NOT NULL,
	DATUM_POSLEDNJEG_KONTAKTA DATE NOT NULL,
	CONSTRAINT ZASTUPA_ZATVORENIK_FK FOREIGN KEY (ID_ZATVORENIKA) REFERENCES ZATVORENIK(ID) ON DELETE CASCADE,
	CONSTRAINT ZASTUPA_ADVOKAT_FK FOREIGN KEY (ID_ADVOKATA) REFERENCES ADVOKAT(ID) ON DELETE CASCADE
);

CREATE TABLE POSECUJE
(
	ID INTEGER PRIMARY KEY,
	ID_ZATVORENIKA INTEGER NOT NULL,
	ID_ADVOKATA INTEGER NOT NULL,
	VREME_POCETKA TIMESTAMP NOT NULL,
	VREME_KRAJA TIMESTAMP NOT NULL,
	CONSTRAINT POSECUJE_ZATVORENIK_FK FOREIGN KEY (ID_ZATVORENIKA) REFERENCES ZATVORENIK(ID) ON DELETE CASCADE,
	CONSTRAINT POSECUJE_ADVOKAT_FK FOREIGN KEY (ID_ADVOKATA) REFERENCES ADVOKAT(ID) ON DELETE CASCADE
);

CREATE TABLE SARADJUJE
(
	ID INTEGER PRIMARY KEY,
	ID_FIRME INTEGER NOT NULL,
	ID_ZATVORSKE_JEDINICE INTEGER NOT NULL,
	CONSTRAINT SARADJUJE_FIRMA_FK FOREIGN KEY (ID_FIRME) REFERENCES FIRMA(ID) ON DELETE CASCADE,
	CONSTRAINT SARADJUJE_ZATVOR_FK FOREIGN KEY (ID_ZATVORSKE_JEDINICE) REFERENCES ZATVORSKA_JEDINICA(ID) ON DELETE CASCADE
);

CREATE TABLE POCINIO
(
	ID INTEGER PRIMARY KEY,
	ID_ZATVORENIKA INTEGER NOT NULL,
	ID_PRESTUPA INTEGER NOT NULL,
	DATUM DATE NOT NULL,
	MESTO_PRESTUPA VARCHAR2(30) NOT NULL,
	CONSTRAINT POCINIO_ZATVORENIK_FK FOREIGN KEY (ID_ZATVORENIKA) REFERENCES ZATVORENIK(ID) ON DELETE CASCADE,
	CONSTRAINT POCINIO_PRESTUP_FK FOREIGN KEY (ID_PRESTUPA) REFERENCES PRESTUP(ID) ON DELETE CASCADE
);

CREATE TABLE FIRMA_KONTAKT
(
	ID INTEGER PRIMARY KEY,
	ID_FIRME INTEGER NOT NULL,
	KONTAKT_TELEFON VARCHAR2(15) NOT NULL,
	CONSTRAINT FIRMA_KONTAKT_FIRMA_FK FOREIGN KEY (ID_FIRME) REFERENCES FIRMA(ID) ON DELETE CASCADE
);

CREATE TABLE FIRMA_ODGOVORNA_LICA
(
	ID INTEGER PRIMARY KEY,
	ID_FIRME INTEGER NOT NULL,
	ODGOVORNO_LICE VARCHAR2(30) NOT NULL,
	CONSTRAINT FIRMA_ODGOVORNA_LICA_FIRMA_FK FOREIGN KEY (ID_FIRME) REFERENCES FIRMA(ID) ON DELETE CASCADE
);

CREATE TABLE STROG_TERMIN_POSETE
(
	ID INTEGER PRIMARY KEY,
	ID_ZATVORSKE_JEDINICE INTEGER NOT NULL,
	TERMIN_POSETE VARCHAR2(30) NOT NULL,
	CONSTRAINT STROG_TERMIN_POSETE_ZATVOR_FK FOREIGN KEY (ID_ZATVORSKE_JEDINICE) REFERENCES ZATVORSKA_JEDINICA(ID) ON DELETE CASCADE
);